Periodically upload intents to cloud
otterize/network-mapper pull request #45
Opened 2022-11-17 13:13 UTC by NetanelBollag

### Description

This PR
### References

Include any links supporting this change such as a:

- GitHub Issue/PR number addressed or fixed
- StackOverflow post
- Related pull requests/issues from other repos

If there are no references, simply delete this section.

### Testing

Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.

Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR and in github.com/otterize/docs

2022-11-17 13:21 UTC, amit7itz commented on src/mapper/cmd/main.go
> +			var empty []string
pass nil instead

2022-11-17 13:24 UTC, amit7itz commented on src/mapper/cmd/main.go
> +		select {
make sure it stops on kill

2022-11-22 09:26 UTC, amit7itz commented
@NetanelBollag change PR destination to develop branch

2022-11-22 11:50 UTC, amit7itz requested changes

2022-11-22 12:05 UTC, NetanelBollag commented on src/mapper/cmd/main.go
> +		go func() {
I prefer showing stuff like starting a go routine and its context handling in main, help to get a quick grasp of the program architecture. Stuff that belong to main IMHO - which configuration the program gets and which tasks it starts

2022-11-22 14:07 UTC, NetanelBollag commented on src/mapper/pkg/config/config.go
> +	CloudEnvironmentKey          = "cloud-environment"
In this case I prefer adding this list to the K8s implementation ticket as stuff to remove when I add it. It is all just in develop right now

2022-11-22 16:23 UTC, amit7itz commented on src/mapper/cmd/main.go
> +		UploadInterval: viper.GetInt(config.UploadIntervalSecondsKey),
Open a `develop` branch there and do it there :) alternatively, you can open a different task to add these parameters to the helm chart, we just need to make sure it happens sometime

2022-11-22 16:28 UTC, amit7itz commented on src/mapper/cmd/main.go
> +		go func() {
I'm still in favor of a method (that receives a context), but it's not critical

2022-11-22 16:42 UTC, amit7itz commented on src/mapper/pkg/resolvers/clouduploader/cloud_upload.go
> +	ServerAddress  string
rename to CloudAPIAddress

2022-11-22 16:52 UTC, amit7itz commented on src/mapper/pkg/resolvers/helpers.go
> +	newIntentFound bool
I would do that with a variable that stores the last change time, and make the thing that tracks the intents changes monitor this value. It's just when it's a boolean you have this doubt about how the IntentsHolder implements this boolean, when a timestamp is a bit more explicit and generic.

2022-11-22 16:53 UTC, amit7itz commented on src/mapper/pkg/resolvers/helpers.go
> +func (i *IntentsHolder) GetIntentsPerService(namespaces []string, markAsRead bool) map[model.OtterizeServiceIdentity][]model.OtterizeServiceIdentity {
Ummm it's a bit inconvenient to need to fill this parameter when all you want to do is read the intents.

2022-11-23 12:17 UTC, NetanelBollag commented on src/mapper/pkg/resolvers/clouduploader/cloud_uploader_test.go
> +}
Replaced it with mocking the API

2022-11-24 10:30 UTC, amit7itz approved these changes

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/cloudapi/cloud_client.go
> +package cloudapi
call it cloudclient as we do in other places

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/cloudapi/discovered_intents_api.go
> +func (CloudAPIImpl) ReportDiscoveredSourcedIntents(ctx context.Context, client graphql.Client, environment string, source string, intents []IntentInput) (*ReportDiscoveredSourcedIntentsResponse, erro
why is this in a separate file? the cloud client is small enough to be contained in a single file

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/cloudapi/cloud_client.go
> +import (
It's a bad practice in go to put underscores in file names because some suffixes actually do black magics (like `_test.go` and `_linux.go`)

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/cloudapi/cloud_client.go
> +	url := fmt.Sprintf("%s/%s", cloudAddress, uri)
it's cloudApiAddress, isn't it?

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/cmd/main.go
> +	cloudClient := clouduploader.NewCloudUploader(intentsHolder, cloudConfig, cloudapi.CloudAPIImpl{})
If you initiate an Impl struct on your own, you are doing something wrong. Add a `NewCloudClient()` method

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/clouduploader/cloud_upload.go
> +func NewCloudUploader(intentsHolder *resolvers.IntentsHolder, config Config, cloudApiImpl cloudapi.CloudAPI) *CloudUploader {
It's not `cloudApiImpl ` it's just a `cloudApi` (or more accurately it's cloudClient)

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/clouduploader/cloud_upload.go
> +	tokenSrc := cfg.TokenSource(context.Background())
Token is part of the cloudclient, not the clouduploader

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/clouduploader/cloud_upload.go
> +func (c *CloudUploader) ReportDiscoveredSourcedIntents(ctx context.Context, client graphql.Client, intents []cloudapi.IntentInput) bool {
should be private, no?

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/clouduploader/cloud_upload.go
> +func ConfigFromViper() Config {
Put this right after the Config struct so the file will be easier to read :)

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/config/config.go
> +	CloudGraphQLEndpointDefault  = "intents/query"
use federation

2022-11-24 10:30 UTC, amit7itz commented on src/mapper/pkg/resolvers/helpers.go
> +	intents.Add(intent)
Move the `Add` into the if, because there's no reason to call it if it is already contained :)

2022-11-27 09:52 UTC, merged